name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: workflows/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
